# This workflow will do a clean install of node dependencies,
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - run: mvn -version
     - run: mvn clean package
     - uses: JS-DevTools/npm-publish@v1
       with:
          token: ${{ secrets.NPM_TOKEN }}
    
    
