# This workflow will do a clean install of node dependencies,
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - run: mvn -version
     - run: mvn clean package
     - uses: ncipollo/release-action@v1
       with:
         tag: latest
         name: Release
    
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
         NODE_AUTH_TOKEN: ${{secrets.NPMJS_AUTOMATION}}
         
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
    
