name: Upload Release

on:
  workflow_dispatch:
  
  release:
    types: [published]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
      - name: Setup GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'

      - name: Setup npmrc 
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@teragrep=https://npm.pkg.github.com/" >> .npmrc
          echo "email=38@teragrep.com" >> .npmrc
                    
      - name: Maven build package
        run: mvn clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  publish:
      if: github.ref == 'refs/heads/automation'
      needs: upload
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14
            registry-url: https://registry.npmjs.org/

        - name: npmrc print
          run: cat .npmrc
          
        - name: Publish
          run: |
            npm publish --ignore-scripts
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPMJS_AUTOMATION}}
