name: Upload Release

on:
  release:
    types: [published]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
      - name: Setup GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'
          
  publish:
      if: github.ref == 'refs/heads/main'
      needs: upload
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14
        - name: Publish
          run: |
              npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
              npm publish --ignore-scripts
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPMJS_AUTOMATION}}