name: Upload Release

on:
  workflow_dispatch:
  
  release:
    types: [published]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
      - name: Setup Packages
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'
                    
      - name: Maven build package
        run: mvn clean package

  publish:
      if: github.ref == 'refs/heads/automation'
      needs: upload
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14
            #registry-url: https://registry.npmjs.org/
        
        - name: Set package registry
          run: npm config set registry https://npm.pkg.github.com
        - name: Github package registry authentication
          run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
        - name: Npm registry authentication
          run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPMJS_TOKEN }}
        - name: Publish packages
          run: npm publish 

        - name: Create Release 
          if: ${{ !startsWith(github.ref, 'refs/tags/') }}
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: v1.0.19-rc4
            release_name: v1.0.19-rc4
          