name: Upload Release

on:
  
  release:
    types: [published]

jobs:
  # Confirm that build was upload successfully
  upload:
    uses: teragrep/rlp_02/.github/workflows/coverity_upload.yaml@automation
          
  publish:
      if: github.ref == 'refs/heads/automation'
      needs: [upload]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14
            #registry-url: https://registry.npmjs.org/
        
        - name: Set package registry
          run: npm config set registry https://npm.pkg.github.com
        - name: Github package registry authentication
          run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
        - name: Npm registry authentication
          run: npm set //registry.npmjs.org/:_authToken ${{secrets.NPMJS_AUTOMATION}}
        - name: Publish packages
          run: npm publish 

          
